### ISSUE TITLE
'mono' Exception when building on Linux

### ISSUE THREAD

**Issue by bokobza** [paulcbetts/refit#316] opened 2017-05-30 11:28 UTC
I'm seeing a problem on Linux.
When running 'dotnet run' on my project I get:
/home/jeremy/.nuget/packages/refit/3.0.1/build/netstandard1.3/refit.targets(35,5): error MSB3073: The command "mono "/home/jeremy/.nuget/packages/refit/3.0.1/build/netstandard1.3/../../tools/InterfaceStubGenerator.exe" "obj/Debug/netstandard1.6/\RefitStubs.g.cs" "/home/jeremy/path_to_project" "obj/Debug/netstandard1.6/RefitParams.rsp"" exited with code 127.

It works fine on Windows.
This is probably happening because I don't have mono installed.
Apart from installing mono, what are my options?

**Comment by matrixkong** [comment] 2017-05-31 06:32
I installed mono, but still go the same exception, it seems like it's using System.Diagnostics.Tracing.EventSource from mscorlib

  Unhandled Exception:
  System.TypeLoadException: Could not load type 'System.Diagnostics.Tracing.EventSource' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
    at Microsoft.CodeAnalysis.Instrumentation.Logger.LogBlock (FunctionId functionId, System.String message, Int32 number, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0
    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText (Microsoft.CodeAnalysis.Text.SourceText text, System.String path, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions options, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0
    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseFile (System.String path, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions options, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0
    at Refit.Generator.InterfaceStubGenerator+<>c.<GenerateInterfaceStubs>b__0_0 (System.String x) [0x00000] in <filename unknown>:0
    at System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[System.String,Microsoft.CodeAnalysis.SyntaxTree].MoveNext () [0x00000] in <filename unknown>:0
    at System.Collections.Generic.List`1[Microsoft.CodeAnalysis.SyntaxTree].AddEnumerable (IEnumerable`1 enumerable) [0x00000] in <filename unknown>:0
    at System.Collections.Generic.List`1[Microsoft.CodeAnalysis.SyntaxTree]..ctor (IEnumerable`1 collection) [0x00000] in <filename unknown>:0
    at System.Linq.Enumerable.ToList[SyntaxTree] (IEnumerable`1 source) [0x00000] in <filename unknown>:0
    at Refit.Generator.InterfaceStubGenerator.GenerateInterfaceStubs (System.String[] paths) [0x00000] in <filename unknown>:0
    at Refit.Generator.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
  [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'System.Diagnostics.Tracing.EventSource' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
    at Microsoft.CodeAnalysis.Instrumentation.Logger.LogBlock (FunctionId functionId, System.String message, Int32 number, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0
    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText (Microsoft.CodeAnalysis.Text.SourceText text, System.String path, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions options, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0
    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseFile (System.String path, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions options, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0
    at Refit.Generator.InterfaceStubGenerator+<>c.<GenerateInterfaceStubs>b__0_0 (System.String x) [0x00000] in <filename unknown>:0
    at System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[System.String,Microsoft.CodeAnalysis.SyntaxTree].MoveNext () [0x00000] in <filename unknown>:0
    at System.Collections.Generic.List`1[Microsoft.CodeAnalysis.SyntaxTree].AddEnumerable (IEnumerable`1 enumerable) [0x00000] in <filename unknown>:0
    at System.Collections.Generic.List`1[Microsoft.CodeAnalysis.SyntaxTree]..ctor (IEnumerable`1 collection) [0x00000] in <filename unknown>:0
    at System.Linq.Enumerable.ToList[SyntaxTree] (IEnumerable`1 source) [0x00000] in <filename unknown>:0
    at Refit.Generator.InterfaceStubGenerator.GenerateInterfaceStubs (System.String[] paths) [0x00000] in <filename unknown>:0
    at Refit.Generator.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by wind-rider** [comment] 2017-06-18 11:57
Probably a duplicate of https://github.com/paulcbetts/refit/issues/310

**Comment by onovotny** [comment] 2017-06-19 13:46
Please try out the latest preview on NuGet: https://www.nuget.org/packages/refit/4.0.0-build.14
You'll need to use the .NET Core 2.0 SDK for this. It may require preview 2 for the correct version checks to work.

**Closed by onovotny** 2017-06-19 13:46 UTC
