### ISSUE TITLE
Refit in vnext (mono)

### ISSUE THREAD

**Issue by buraktamturk** [paulcbetts/refit#144] opened 2015-05-09 18:47 UTC
Hello,

Not sure if it's Retrofit's problem or Microsoft's bug or me. But I can't get it working on vnext mono (os x). I get exception with the following message.

InterfaceName doesn't look like a Refit interface. Make sure it has at least one method with a Refit HTTP method attribute and Refit is installed in the project.

However, I define the class like as this.

```
public interface InterfaceName {
    [Get("/account")]
    Task<WebResponse<Account>> account(string token);
}
```

I tried to look at the code of the refit to find the cause of the error. I am coming from java, it seems compile time annotation processing doesn't work. Which step is missing at compile time? i'll open a issue on where it belongs.

**Comment by paulcbetts** [comment] 2015-05-09 19:02
Do you have the RefitStubs.cs file in your project? Is that file non-empty? Also, interfaces in C# always start with the letter "I" (i.e. IMyCoolThing)

**Comment by buraktamturk** [comment] 2015-05-09 19:10
I can't find the file in the project folder, looked everywhere in the project folder. Perhaps, it's not builded or copied by the dnvm (was kvm before). (I masked the interface name wrongly, and it starts with I)

**Comment by paulcbetts** [comment] 2015-05-09 19:41
`dnvm` is not Mono, Refit most likely doesn't work there yet

**Comment by RTodorov** [comment] 2015-10-12 15:40
Does it work with a Console Application using Mono / .NET 4.5 profile ? Because I'm not getting the stubs file to be generated either.

Thanks

**Comment by RTodorov** [comment] 2015-10-12 15:55
If I manually generate the stubs file using the InterfaceStubGenerator.exe I'll get this:

Symbol file /Users/rtodorov/Projects/MyProject.Cmd/bin/Debug/Refit.dll.mdb doesn't match image (null)

**Comment by RTodorov** [comment] 2015-10-14 11:06
Ok, so, I tested on Visual Studio and it worked, the problem is that it doesn't work on Mono with Xamarin. Apparently Xamarin only works for mobile development. Would be nice to have it working also for web projects, I would open a PR but I don't even know where to begin...

**Comment by onovotny** [comment] 2017-01-21 16:18
Closing for now

**Closed by onovotny** 2017-01-21 16:18 UTC
