### ISSUE TITLE
Generic interfaces do not support parameters

### ISSUE THREAD

**Issue by enagy27** [paulcbetts/refit#211] opened 2015-12-29 20:48 UTC
Trying to apply parameters to the refit attributes of a generic interface causes RestService.For<> (more specifically verifyUrlPathIsSane) to fail and throw an ArgumentException due to improper formatting, where only the parameters are being validated, because this method does not know that a relative path has already been supplied on instantiation of the client (of course, even if it did, it wouldn't know how much of the provided URL is the relative path specific to my class)

**Comment by ahmedalejo** [comment] 2015-12-30 17:37
@airwareic try adding non-cofidential code samples to reproduce the issue you are facing.

**Comment by airwareic** [comment] 2015-12-31 06:15
So the core of this issue, as far as I can see, is the expectation that the attributes match the format:
'[Get("/foo?param={param}")]'
Whereas generic definitions will be set up via:
'RestService.For<IBar>("http://example.com/foo");'
This means my generic definition, seeing as it needs to be provided the relative path via instantiation of the service itself will become:
'[Get("?param={param}")]'

At this point, the attribute declaration is no longer a valid relative path, according to the current validateUriIsSane (or something similar), resulting in a thrown ArgumentException. Having looked into this at a thousand-foot level I believe that so long as the validation method is modified to account for this case, everything operates as expected (still needs testing to be sure). I may have some time to look into this myself- I'm curious to know whether this validation could be done using the full URI (the instantiated client's base plus the attributed relative URI, possibly with variables replaced). Additionally, I'm curious to know why UriTemplates weren't used instead (not sure if this is counter-PCL).

@ahmedalejo is this enough detail, or would you like the full definition of my generic interface?

**Comment by ahmedalejo** [comment] 2016-01-01 03:52
@airwareic that would be great!

**Comment by onovotny** [comment] 2018-01-29 21:00
Closing due to age. Please reopen with a sample repro if still an issue.

**Closed by onovotny** 2018-01-29 21:00 UTC
